---
all:
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5985
    ansible_winrm_transport: ntlm
    ansible_password: "Change.me123!" #REPLACE
    path_to_download: "C:\\Windows\\System32" #REPLACE
    path_for_comm: "C:\\Windows\\Temp"
    binary_name: "SysUpdateSvc.exe" # Replace
    binary_location: "/home/president/server/{{ binary_name }}}"
    service_name: "SysUpdateSvc" # Replace
    reg_key_param: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\"
    reg_restrict: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services"
    service_for_injection: "NlaSvc" #Try spooler just as idea

    hosts:
      children:
        windows_servers:
          vars:
            ansible_user: "president"
          hosts:
            # ---- 10.x network ----
            10.[1:20].1.1:  # Pyramids
              file_to_download: "filename"
            # ---- 192.168.x network ----
            192.168.[1:20].3:  # Wright Brothers 
              file_to_download: "filename"
        windows_workstations:
          vars:
            ansible_user: "president"
          hosts:
            # ---- 10.x network ----
            10.[1:20].1.2:  # First Olympics
              file_to_download: "filename"
            10.[1:20].1.3:  # Silk Road
              file_to_download: "filename"
            # ---- 192.168.x network ----
            192.168.[1:20].4:  # Moon Landing
              file_to_download: "filename"