---
all:
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5985
    ansible_winrm_transport: ntlm
    ansible_user: "president" #REPLACE
    ansible_password: "Change.me123!" #REPLACE
    path_to_download: "C:\\Users\\president\\Desktop" #REPLACE
    path_for_comm: "C:\\Windows\\Temp"
    binary_location: "/Windows-Scripts"
    binary_name: "BITS_TEST.exe"
    service_name: "bitHelp"
    reg_key_param: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\"
    reg_restrict: "HKLM\\SYSTEM\\CurrentControlSet\\Services\\{{ service_name }}"
    service_for_injection: "NlaSvc"

  children:
    team01:
      hosts:
        1.1.1.1: 
          file_to_download: "/dns.txt"
        2.2.2.2:
          file_to_download: "/workstation.txt"
    team02:
      hosts:
        1.1.1.1: 
          file_to_download: "/dns.txt"
        2.2.2.2:
          file_to_download: "/workstation.txt"
            
      